import { defineConfig, devices } from '@playwright/test'
import 'dotenv/config'

/**
 * Playwright config — see testing-policy.md for the full testing rules.
 *
 * Two projects always run: chromium-desktop AND chromium-mobile (iPhone 13).
 * Mobile is the primary product target per CLAUDE.md, so any UI test that
 * passes desktop but breaks mobile must fail the suite.
 */
export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html', { open: 'never' }], ['list']],

  use: {
    baseURL: 'http://localhost:5173',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    // storageState used by tests that require auth — generated by global-setup.js
    // when VITE_TEST_EMAIL + VITE_TEST_PASSWORD are present in .env.test.
  },

  projects: [
    {
      name: 'chromium-desktop',
      use: { ...devices['Desktop Chrome'] }
    },
    {
      // iPhone 13 viewport but forced onto Chromium so we don't pull WebKit
      // into the install. Chromium-only is the project rule.
      name: 'chromium-mobile',
      use: { ...devices['iPhone 13'], browserName: 'chromium' }
    }
  ],

  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:5173',
    reuseExistingServer: !process.env.CI,
    timeout: 120 * 1000
  }
})
