-- This file documents the schema for tables related to matches.
-- Note: This is for documentation purposes. Apply changes via ALTER statements or by running CREATE statements on a fresh database.

-- Matches Table
CREATE TABLE public.matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  opponent TEXT,
  match_date DATE,
  score_for INTEGER DEFAULT 0,
  score_against INTEGER DEFAULT 0,
  my_goals INTEGER DEFAULT 0,
  assists INTEGER DEFAULT 0,
  tackles INTEGER DEFAULT 0,
  interceptions INTEGER DEFAULT 0,
  clearances INTEGER DEFAULT 0,
  dribbles INTEGER DEFAULT 0,
  successful_passes INTEGER DEFAULT 0,
  unsuccessful_passes INTEGER DEFAULT 0,
  fouls INTEGER DEFAULT 0,
  own_goals INTEGER DEFAULT 0,
  position_played TEXT, -- New field
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Goals Table
CREATE TABLE public.goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES public.matches(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  goal_type TEXT,
  quadrant INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Shots Table
CREATE TABLE public.shots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES public.matches(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  on_target BOOLEAN,
  quadrant INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Goalkeeper Match Stats Table (New Table)
CREATE TABLE public.goalkeeper_match_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES public.matches(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  saves INTEGER DEFAULT 0,
  catches INTEGER DEFAULT 0,
  punches INTEGER DEFAULT 0,
  goals_conceded INTEGER DEFAULT 0,
  penalties_saved INTEGER DEFAULT 0,
  successful_passes INTEGER DEFAULT 0,
  unsuccessful_passes INTEGER DEFAULT 0,
  goals INTEGER DEFAULT 0,
  assists INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(match_id, user_id)
);
