-- Practice tracker: drill templates + per-session log entries.
-- See plan: a user creates a named drill once (juggles, shots outside the box,
-- sprint, etc.) and logs repeat sessions over time to track improvement.

-- Drill templates
CREATE TABLE IF NOT EXISTS public.practice_drills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  metric_type TEXT NOT NULL CHECK (metric_type IN ('count','ratio','time','distance','speed')),
  unit TEXT,
  lower_is_better BOOLEAN DEFAULT FALSE,
  target_value NUMERIC,
  notes TEXT,
  archived BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Individual sessions
CREATE TABLE IF NOT EXISTS public.practice_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drill_id BIGINT REFERENCES public.practice_drills(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  session_date DATE NOT NULL,
  primary_value NUMERIC NOT NULL,
  secondary_value NUMERIC,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_practice_drills_user         ON public.practice_drills(user_id);
CREATE INDEX IF NOT EXISTS idx_practice_sessions_drill_date ON public.practice_sessions(drill_id, session_date DESC);
CREATE INDEX IF NOT EXISTS idx_practice_sessions_user_date  ON public.practice_sessions(user_id, session_date DESC);

ALTER TABLE public.practice_drills   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.practice_sessions ENABLE ROW LEVEL SECURITY;

-- RLS: practice_drills
DROP POLICY IF EXISTS "Users can view own practice drills"   ON public.practice_drills;
CREATE POLICY "Users can view own practice drills"   ON public.practice_drills
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own practice drills" ON public.practice_drills;
CREATE POLICY "Users can insert own practice drills" ON public.practice_drills
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own practice drills" ON public.practice_drills;
CREATE POLICY "Users can update own practice drills" ON public.practice_drills
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own practice drills" ON public.practice_drills;
CREATE POLICY "Users can delete own practice drills" ON public.practice_drills
  FOR DELETE USING (auth.uid() = user_id);

-- RLS: practice_sessions
DROP POLICY IF EXISTS "Users can view own practice sessions"   ON public.practice_sessions;
CREATE POLICY "Users can view own practice sessions"   ON public.practice_sessions
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own practice sessions" ON public.practice_sessions;
CREATE POLICY "Users can insert own practice sessions" ON public.practice_sessions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own practice sessions" ON public.practice_sessions;
CREATE POLICY "Users can update own practice sessions" ON public.practice_sessions
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own practice sessions" ON public.practice_sessions;
CREATE POLICY "Users can delete own practice sessions" ON public.practice_sessions
  FOR DELETE USING (auth.uid() = user_id);
