-- Extends the practice tracker with a 'shot_map' metric type and a child
-- table of per-shot placements (free X/Y on a goal frame, plus outcome).
-- Used in the LogSession UI to mark each shot during shooting drills.

-- Replace the CHECK constraint on practice_drills.metric_type to add 'shot_map'.
ALTER TABLE public.practice_drills
  DROP CONSTRAINT IF EXISTS practice_drills_metric_type_check;

ALTER TABLE public.practice_drills
  ADD CONSTRAINT practice_drills_metric_type_check
  CHECK (metric_type IN ('count','ratio','time','distance','speed','shot_map'));

-- One row per individual shot inside a shot_map session.
CREATE TABLE IF NOT EXISTS public.practice_shot_placements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES public.practice_sessions(id) ON DELETE CASCADE NOT NULL,
  drill_id BIGINT REFERENCES public.practice_drills(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  x_pct NUMERIC NOT NULL,  -- 0–100, horizontal position inside the goal frame
  y_pct NUMERIC NOT NULL,  -- 0–100, vertical position inside the goal frame
  outcome TEXT NOT NULL CHECK (outcome IN ('goal','save','miss')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_practice_shot_placements_session ON public.practice_shot_placements(session_id);
CREATE INDEX IF NOT EXISTS idx_practice_shot_placements_drill   ON public.practice_shot_placements(drill_id);
CREATE INDEX IF NOT EXISTS idx_practice_shot_placements_user    ON public.practice_shot_placements(user_id);

ALTER TABLE public.practice_shot_placements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own shot placements"   ON public.practice_shot_placements;
CREATE POLICY "Users can view own shot placements"   ON public.practice_shot_placements
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own shot placements" ON public.practice_shot_placements;
CREATE POLICY "Users can insert own shot placements" ON public.practice_shot_placements
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own shot placements" ON public.practice_shot_placements;
CREATE POLICY "Users can update own shot placements" ON public.practice_shot_placements
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own shot placements" ON public.practice_shot_placements;
CREATE POLICY "Users can delete own shot placements" ON public.practice_shot_placements
  FOR DELETE USING (auth.uid() = user_id);
