-- Opt-in tactical heatmap tracking (matches only) + standalone load management log.
-- enable_heatmap_tracking is a global per-user toggle; track_heatmap_for_match is the
-- per-match opt-in. match_heatmap_points stores tapped pitch coordinates (0-100).
-- load_entries is a standalone quick-log of training/match minutes + self-reported fatigue.

-- Heatmap tracking is on by default; users can opt out per-profile or per-match.
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS enable_heatmap_tracking BOOLEAN DEFAULT TRUE;
ALTER TABLE public.user_profiles
  ALTER COLUMN enable_heatmap_tracking SET DEFAULT TRUE;

ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS track_heatmap_for_match BOOLEAN DEFAULT TRUE;
ALTER TABLE public.matches
  ALTER COLUMN track_heatmap_for_match SET DEFAULT TRUE;

-- Each point records what event happened (tackle, pass, etc.) and where.
CREATE TABLE IF NOT EXISTS public.match_heatmap_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES public.matches(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  x_pct NUMERIC(5,2) NOT NULL,
  y_pct NUMERIC(5,2) NOT NULL,
  event_type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.match_heatmap_points
  ADD COLUMN IF NOT EXISTS event_type TEXT;

CREATE TABLE IF NOT EXISTS public.load_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  entry_date DATE NOT NULL,
  minutes INTEGER NOT NULL CHECK (minutes >= 0 AND minutes <= 600),
  fatigue INTEGER NOT NULL CHECK (fatigue >= 1 AND fatigue <= 10),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_match_heatmap_points_match ON public.match_heatmap_points(match_id);
CREATE INDEX IF NOT EXISTS idx_match_heatmap_points_user  ON public.match_heatmap_points(user_id);
CREATE INDEX IF NOT EXISTS idx_load_entries_user_date     ON public.load_entries(user_id, entry_date DESC);

ALTER TABLE public.match_heatmap_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.load_entries         ENABLE ROW LEVEL SECURITY;

-- RLS: match_heatmap_points
DROP POLICY IF EXISTS "Users can view own heatmap points"   ON public.match_heatmap_points;
CREATE POLICY "Users can view own heatmap points"   ON public.match_heatmap_points
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own heatmap points" ON public.match_heatmap_points;
CREATE POLICY "Users can insert own heatmap points" ON public.match_heatmap_points
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own heatmap points" ON public.match_heatmap_points;
CREATE POLICY "Users can delete own heatmap points" ON public.match_heatmap_points
  FOR DELETE USING (auth.uid() = user_id);

-- RLS: load_entries
DROP POLICY IF EXISTS "Users can view own load entries"   ON public.load_entries;
CREATE POLICY "Users can view own load entries"   ON public.load_entries
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own load entries" ON public.load_entries;
CREATE POLICY "Users can insert own load entries" ON public.load_entries
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own load entries" ON public.load_entries;
CREATE POLICY "Users can update own load entries" ON public.load_entries
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own load entries" ON public.load_entries;
CREATE POLICY "Users can delete own load entries" ON public.load_entries
  FOR DELETE USING (auth.uid() = user_id);
