-- 0017_ai_chat_history.sql
--
-- Server-side persistence for the AI Coach's MULTIPLE conversations, so chats
-- sync across devices. Adds an `ai_conversations` table and links each message
-- to a conversation. `ai_chat_messages` may already exist (it was created
-- ad-hoc for the old single-chat coach) — this is written to be safe either way.
--
-- Apply manually in the Supabase SQL editor (no migration runner in this repo).

-- ── Conversations ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ai_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL DEFAULT 'New chat',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_conversations_user
  ON public.ai_conversations(user_id, updated_at DESC);

-- ── Messages (ensure the table exists, then link to a conversation) ──────────
CREATE TABLE IF NOT EXISTS public.ai_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role TEXT NOT NULL,
  content TEXT DEFAULT '',
  match_card JSONB,
  calendar_days JSONB,
  time_label TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.ai_chat_messages
  ADD COLUMN IF NOT EXISTS conversation_id BIGINT
  REFERENCES public.ai_conversations(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_ai_chat_messages_conversation
  ON public.ai_chat_messages(conversation_id, created_at);

-- ── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "own conversations select" ON public.ai_conversations;
CREATE POLICY "own conversations select" ON public.ai_conversations
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "own conversations insert" ON public.ai_conversations;
CREATE POLICY "own conversations insert" ON public.ai_conversations
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "own conversations update" ON public.ai_conversations;
CREATE POLICY "own conversations update" ON public.ai_conversations
  FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "own conversations delete" ON public.ai_conversations;
CREATE POLICY "own conversations delete" ON public.ai_conversations
  FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "own messages select" ON public.ai_chat_messages;
CREATE POLICY "own messages select" ON public.ai_chat_messages
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "own messages insert" ON public.ai_chat_messages;
CREATE POLICY "own messages insert" ON public.ai_chat_messages
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "own messages delete" ON public.ai_chat_messages;
CREATE POLICY "own messages delete" ON public.ai_chat_messages
  FOR DELETE USING (auth.uid() = user_id);
