-- 0020_admin_and_content.sql
--
-- Admin role + editable site content + premium waitlist.
-- * is_admin gates the /admin panel and admin-only writes.
-- * site_content holds editable copy/pricing (the premium screen reads it;
--   public can SELECT, only admins can write).
-- * waitlist captures premium "Notify me" sign-ups.
--
-- After applying: flip your own account to admin, e.g.
--   UPDATE public.user_profiles SET is_admin = true WHERE user_id = '<your-uid>';
--
-- Apply manually in the Supabase SQL editor (no migration runner in this repo).

ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false;

-- ── Editable site content ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.site_content (
  id TEXT PRIMARY KEY,
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "site_content public read" ON public.site_content;
CREATE POLICY "site_content public read" ON public.site_content
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "site_content admin insert" ON public.site_content;
CREATE POLICY "site_content admin insert" ON public.site_content
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND is_admin)
  );

DROP POLICY IF EXISTS "site_content admin update" ON public.site_content;
CREATE POLICY "site_content admin update" ON public.site_content
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND is_admin)
  );

-- ── Premium waitlist ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_waitlist_created ON public.waitlist(created_at DESC);

ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "waitlist own insert" ON public.waitlist;
CREATE POLICY "waitlist own insert" ON public.waitlist
  FOR INSERT WITH CHECK (auth.uid() = user_id);
