-- 0021_phase1_features.sql
--
-- Phase 1 features: season goals/pacing, Pro Vision media metering, club
-- colours (2-tone), and an early-access flag.
--
-- Apply manually in the Supabase SQL editor (no migration runner in this repo).

-- ── Season goals (per user, per season; season_id null = all-time) ───────────
CREATE TABLE IF NOT EXISTS public.season_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  season_id TEXT,                       -- stringified season id, or NULL for all-time
  goals_target INTEGER,
  assists_target INTEGER,
  rating_target NUMERIC(4,2),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, season_id)
);

ALTER TABLE public.season_goals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own season_goals" ON public.season_goals;
CREATE POLICY "own season_goals" ON public.season_goals
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ── Pro Vision media usage (15 uploads / month soft cap) ─────────────────────
CREATE TABLE IF NOT EXISTS public.pro_media_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  period TEXT NOT NULL,                 -- 'YYYY-MM'
  count INTEGER NOT NULL DEFAULT 0,
  UNIQUE (user_id, period)
);

ALTER TABLE public.pro_media_usage ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own pro_media_usage" ON public.pro_media_usage;
CREATE POLICY "own pro_media_usage" ON public.pro_media_usage
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ── Profile: club secondary colour + early access ────────────────────────────
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS secondary_color TEXT;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS early_access BOOLEAN DEFAULT false;
