-- 0022_admin_control_center.sql
--
-- Admin control-center support:
-- * banned_until mirrors Supabase Auth's native ban onto the profile so the
--   admin user list can filter/show banned users cheaply (the real login block
--   is the native auth ban set by the `admin` edge function).
-- * admin_audit_log records every privileged admin action. Service-role only —
--   no client RLS policy, so the anon/auth client can never read or write it;
--   only the `admin` edge function (service role) touches it.
-- * helper indexes for user/match search and audit ordering.
--
-- Apply manually in the Supabase SQL editor (no migration runner in this repo).

-- ── Soft ban mirror on the profile ───────────────────────────────────────────
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS banned_until TIMESTAMPTZ;

-- ── Admin audit log (service-role only) ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_user_id UUID,
  target_id TEXT,
  detail JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS on, but intentionally NO policies: the anon/auth client gets zero rows.
-- The service-role `admin` edge function bypasses RLS to insert/select.
ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_audit_created ON public.admin_audit_log(created_at DESC);

-- ── Search / filter helpers ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_profiles_player_name_lower
  ON public.user_profiles (lower(player_name));
CREATE INDEX IF NOT EXISTS idx_profiles_tier
  ON public.user_profiles (subscription_tier);
