-- 0023_phase2_features.sql
--
-- Phase 2 features:
-- * Coach/Scout share link — an unguessable, revocable token on the profile.
--   The public read-only dashboard is served by the `shared-dashboard` edge
--   function (service role), so no cross-user SELECT policy is needed here.
-- * Profile analytics — anonymous view/expand events. Any authenticated user
--   may INSERT (log a view of someone's profile/card); only the target owner
--   may SELECT their own aggregates (no edge function needed).
--
-- Apply manually in the Supabase SQL editor (no migration runner in this repo).

-- ── Share link ───────────────────────────────────────────────────────────────
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS share_token TEXT,
  ADD COLUMN IF NOT EXISTS share_enabled BOOLEAN DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_share_token
  ON public.user_profiles (share_token) WHERE share_token IS NOT NULL;

-- ── Profile analytics (anonymous events) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profile_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('profile_view', 'card_expand')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_profile_events_target
  ON public.profile_events (target_user_id, created_at DESC);

ALTER TABLE public.profile_events ENABLE ROW LEVEL SECURITY;

-- Any signed-in user can log an event (no viewer identity is stored → anonymous).
DROP POLICY IF EXISTS "profile_events authed insert" ON public.profile_events;
CREATE POLICY "profile_events authed insert" ON public.profile_events
  FOR INSERT TO authenticated WITH CHECK (true);

-- Only the profile owner can read their own analytics.
DROP POLICY IF EXISTS "profile_events owner read" ON public.profile_events;
CREATE POLICY "profile_events owner read" ON public.profile_events
  FOR SELECT USING (auth.uid() = target_user_id);
